/* =========================================================
   data.js — fonte única de dados do Portal de Teyvat
   (ELEMENTS, ACHIEVEMENTS, ACTIVITIES)
   ========================================================= */

const ELEMENTS = {
  pyro: {
    key: "pyro", name: "PYRO", vision: "assets/visions/pyro.png",
    primary: "#ff6a3d", secondary: "#ffb45c", glow: "rgba(255,106,61,.55)",
    kicker: "A chama que nunca se apaga",
    desc: "Sua energia é intensa, apaixonada e impossível de ignorar. Você enfrenta a vida de peito aberto, movido por paixão e coragem, e não tem medo de arriscar tudo por aquilo em que acredita.",
    traits: ["Paixão", "Coragem", "Determinação", "Impulsividade produtiva", "Lealdade intensa"],
    quote: "\u201COnde há vontade, há uma chama que ilumina o caminho.\u201D",
    character: "hutao", characterName: "Hu Tao",
  },
  hydro: {
    key: "hydro", name: "HYDRO", vision: "assets/visions/hydro.png",
    primary: "#3aa0ff", secondary: "#8fe3ff", glow: "rgba(58,160,255,.5)",
    kicker: "A correnteza que tudo acolhe",
    desc: "Você flui com empatia e sensibilidade, adaptando-se às pessoas e situações sem perder sua essência. Sua força está em curar, conectar e entender o que os outros sentem.",
    traits: ["Empatia", "Adaptabilidade", "Intuição", "Serenidade", "Cuidado com os outros"],
    quote: "\u201CComo a água, encontro sempre um caminho.\u201D",
    character: "furina", characterName: "Furina",
  },
  anemo: {
    key: "anemo", name: "ANEMO", vision: "assets/visions/anemo.png",
    primary: "#4fd8b3", secondary: "#bff5da", glow: "rgba(79,216,179,.5)",
    kicker: "O vento que não se prende a nada",
    desc: "Liberdade é sua palavra de ordem. Você valoriza a independência, adora descobrir novos horizontes e não gosta de ficar preso a rotinas ou expectativas alheias.",
    traits: ["Liberdade", "Criatividade", "Independência", "Adaptabilidade", "Espírito aventureiro"],
    quote: "\u201CO vento não escolhe direção; ele a cria.\u201D",
    character: "kazuha", characterName: "Kazuha",
  },
  electro: {
    key: "electro", name: "ELECTRO", vision: "assets/visions/electro.png",
    primary: "#b06bff", secondary: "#e0b3ff", glow: "rgba(176,107,255,.5)",
    kicker: "A centelha que muda tudo",
    desc: "Sua mente é rápida e sua vontade, elétrica. Você busca autonomia, tem opiniões fortes e prefere agir por conta própria a esperar que outros decidam por você.",
    traits: ["Ambição", "Independência", "Inteligência", "Confiança", "Espírito revolucionário"],
    quote: "\u201CA mudança começa com uma única faísca.\u201D",
    character: "raiden", characterName: "Raiden Shogun",
  },
  dendro: {
    key: "dendro", name: "DENDRO", vision: "assets/visions/dendro.png",
    primary: "#8bd44e", secondary: "#d9e88a", glow: "rgba(139,212,78,.5)",
    kicker: "A raiz que sustenta o crescimento",
    desc: "Curiosidade e sabedoria guiam seus passos. Você busca entender o mundo com profundidade, valoriza o crescimento pessoal e tem paciência para cultivar o que realmente importa.",
    traits: ["Sabedoria", "Curiosidade", "Paciência", "Empatia racional", "Crescimento constante"],
    quote: "\u201CToda grande árvore já foi uma semente paciente.\u201D",
    character: "nahida", characterName: "Nahida",
  },
  cryo: {
    key: "cryo", name: "CRYO", vision: "assets/visions/cryo.png",
    primary: "#9fe0ff", secondary: "#ffffff", glow: "rgba(159,224,255,.5)",
    kicker: "O silêncio que revela força",
    desc: "Você mantém a compostura mesmo sob pressão. Por trás da sua calma reservada existe uma determinação firme e um senso de justiça que não se abala facilmente.",
    traits: ["Disciplina", "Clareza mental", "Resiliência", "Honestidade", "Firmeza"],
    quote: "\u201CO gelo não quebra; ele apenas espera o momento certo.\u201D",
    character: "ayaka", characterName: "Ayaka",
  },
  geo: {
    key: "geo", name: "GEO", vision: "assets/visions/geo.png",
    primary: "#e0a94a", secondary: "#ffd98a", glow: "rgba(224,169,74,.5)",
    kicker: "A rocha que não se abala",
    desc: "Estabilidade e confiança são a sua marca. Você é a pessoa em quem os outros se apoiam, alguém que constrói com paciência e não se deixa levar por modismos passageiros.",
    traits: ["Estabilidade", "Confiabilidade", "Paciência", "Praticidade", "Senso de justiça"],
    quote: "\u201CMontanhas não se apressam, e ainda assim chegam ao topo.\u201D",
    character: "zhongli", characterName: "Zhongli",
  },
};
const ELEMENT_KEYS = Object.keys(ELEMENTS);

/* ------------------- PERSONAGENS (Quiz "Qual personagem combina comigo?") ------------------- */
const CHARACTERS = {
  kazuha: {
    key: "kazuha", name: "Kaedehara Kazuha", element: "anemo", region: "Inazuma",
    title: "O samurai errante",
    traits: ["Serenidade", "Poesia", "Lealdade silenciosa", "Espírito livre"],
    desc: "Kazuha carrega o peso do passado com leveza, encontrando beleza mesmo na dor. Como você, ele valoriza a liberdade de seguir seu próprio caminho sem perder o cuidado com quem ama.",
    quote: "\u201CQue o vento te leve para onde seu coração precisar ir.\u201D",
    image: "assets/characters/kazuha.png",
  },
  furina: {
    key: "furina", name: "Furina", element: "hydro", region: "Fontaine",
    title: "A ex-Arconte teatral",
    traits: ["Teatralidade", "Sensibilidade oculta", "Carisma", "Resiliência"],
    desc: "Por trás da encenação grandiosa de Furina existe alguém que sente profundamente e carrega responsabilidades enormes em silêncio — assim como você, que sabe brilhar sem esconder o que realmente importa.",
    quote: "\u201CO show deve continuar, mesmo quando o coração pesa.\u201D",
    image: "assets/characters/furina.png",
  },
  raiden: {
    key: "raiden", name: "Raiden Shogun (Ei)", element: "electro", region: "Inazuma",
    title: "A Shogun da Eternidade",
    traits: ["Disciplina", "Busca pela perfeição", "Proteção", "Firmeza"],
    desc: "A Raiden Shogun busca um ideal de eternidade através de disciplina inabalável. Assim como você, ela lidera com convicção e nunca abre mão daquilo em que acredita.",
    quote: "\u201CA eternidade não se conquista sem sacrifício e disciplina.\u201D",
    image: "assets/characters/raiden.png",
  },
  nahida: {
    key: "nahida", name: "Nahida", element: "dendro", region: "Sumeru",
    title: "A Menor Sábia",
    traits: ["Sabedoria", "Curiosidade", "Empatia", "Crescimento"],
    desc: "Apesar de jovem, Nahida enxerga o mundo com uma sabedoria rara e um desejo genuíno de entender os outros. Você compartilha dessa mesma curiosidade sincera pelo que move as pessoas.",
    quote: "\u201CTodo conhecimento começa com uma pergunta sincera.\u201D",
    image: "assets/characters/nahida.png",
  },
  zhongli: {
    key: "zhongli", name: "Zhongli", element: "geo", region: "Liyue",
    title: "O Arconte Contratual",
    traits: ["Sabedoria", "Paciência", "Tradição", "Justiça"],
    desc: "Zhongli valoriza contratos, tradição e justiça acima de tudo, agindo sempre com calma e propósito. Como ele, você constrói confiança através da consistência e do respeito pelas próprias palavras.",
    quote: "\u201CUm contrato bem feito vale mais que mil promessas vazias.\u201D",
    image: "assets/characters/zhongli.png",
  },
  hutao: {
    key: "hutao", name: "Hu Tao", element: "pyro", region: "Liyue",
    title: "A 77ª Diretora do Wangsheng",
    traits: ["Bom humor", "Filosofia sobre a vida", "Espontaneidade", "Paixão pelo trabalho"],
    desc: "Hu Tao encara a vida (e a morte) com um humor único e uma paixão contagiante por tudo o que faz. Assim como ela, você sabe rir das dificuldades sem perder a profundidade por trás disso.",
    quote: "\u201CA vida é curta demais para ser vivida sem graça.\u201D",
    image: "assets/characters/hutao.png",
  },
  ayaka: {
    key: "ayaka", name: "Kamisato Ayaka", element: "cryo", region: "Inazuma",
    title: "A Princesa Cristalina",
    traits: ["Elegância", "Disciplina", "Dedicação", "Calor escondido"],
    desc: "Ayaka equilibra deveres rígidos com um coração genuinamente caloroso por trás da compostura. Você também sabe manter a elegância sob pressão, sem deixar de se importar profundamente com quem ama.",
    quote: "\u201CA verdadeira força se mostra na gentileza silenciosa.\u201D",
    image: "assets/characters/ayaka.png",
  },
  venti: {
    key: "venti", name: "Venti", element: "anemo", region: "Mondstadt",
    title: "O Arconte da Liberdade",
    traits: ["Liberdade", "Espontaneidade", "Sabedoria disfarçada", "Compaixão"],
    desc: "Venti esconde uma sabedoria profunda atrás de um jeito descontraído e brincalhão, sempre valorizando a liberdade acima de tudo. Você compartilha esse espírito livre, mesmo levando a vida com leveza.",
    quote: "\u201CDeixe que o vento decida — ele sempre sabe o caminho certo.\u201D",
    image: "assets/characters/venti.png",
  },
  xiao: {
    key: "xiao", name: "Xiao", element: "anemo", region: "Liyue",
    title: "O Yaksha Conquistador",
    traits: ["Proteção silenciosa", "Sacrifício", "Solidão", "Lealdade"],
    desc: "Xiao carrega um fardo pesado sozinho para proteger os outros, sem esperar reconhecimento. Assim como ele, você entende que cuidar de alguém às vezes significa agir em silêncio.",
    quote: "\u201CCarregarei esse peso, para que outros não precisem.\u201D",
    image: "assets/characters/xiao.png",
  },
  neuvillette: {
    key: "neuvillette", name: "Neuvillette", element: "hydro", region: "Fontaine",
    title: "O Cronista Supremo",
    traits: ["Imparcialidade", "Serenidade", "Justiça", "Perspectiva ampla"],
    desc: "Neuvillette julga com uma calma quase sobrenatural, sempre buscando a verdade mais justa possível. Você também tende a olhar o quadro geral antes de tirar conclusões precipitadas.",
    quote: "\u201CA verdade, como a água, sempre encontra seu nível.\u201D",
    image: "assets/characters/neuvillette.png",
  },
  arlecchino: {
    key: "arlecchino", name: "Arlecchino", element: "pyro", region: "Snezhnaya",
    title: "A Quarta Fatui Harbinger",
    traits: ["Determinação implacável", "Proteção feroz", "Pragmatismo", "Comando natural"],
    desc: "Arlecchino protege os seus com uma ferocidade que não aceita fraquezas, liderando com pulso firme. Você também sabe ser implacável quando o que está em jogo é proteger quem importa.",
    quote: "\u201CQuem ameaça minha família responde a mim.\u201D",
    image: "assets/characters/arlecchino.png",
  },
  navia: {
    key: "navia", name: "Navia", element: "geo", region: "Fontaine",
    title: "A Presidente da Spina di Rosula",
    traits: ["Liderança generosa", "Elegância", "Determinação", "Senso de justiça"],
    desc: "Navia lidera com graça e força, sempre disposta a proteger quem confia nela. Assim como ela, você une elegância e determinação para fazer o que é certo.",
    quote: "\u201CUma verdadeira líder nunca abandona os seus.\u201D",
    image: "assets/characters/navia.png",
  },
  wanderer: {
    key: "wanderer", name: "Wanderer (Scaramouche)", element: "anemo", region: "Sumeru",
    title: "O Vagabundo",
    traits: ["Orgulho", "Ironia afiada", "Autoconhecimento em construção", "Independência"],
    desc: "O Wanderer esconde inseguranças profundas atrás de um orgulho afiado, mas está em constante evolução. Você também sabe usar a ironia como defesa enquanto ainda descobre quem realmente é.",
    quote: "\u201CNão preciso da aprovação de ninguém para seguir em frente.\u201D",
    image: "assets/characters/wanderer.png",
  },
  yaemiko: {
    key: "yaemiko", name: "Yae Miko", element: "electro", region: "Inazuma",
    title: "A Grande Guuji do Grand Narukami",
    traits: ["Astúcia", "Humor provocador", "Estratégia", "Mistério"],
    desc: "Yae Miko é astuta e adora provocar, mas por trás disso existe uma mente estrategista brilhante. Você também sabe usar o charme e a inteligência para conseguir exatamente o que quer.",
    quote: "\u201COra, ora... achou mesmo que seria tão simples?\u201D",
    image: "assets/characters/yaemiko.png",
  },
  alhaitham: {
    key: "alhaitham", name: "Alhaitham", element: "dendro", region: "Sumeru",
    title: "O Ex-Acadêmico Principal",
    traits: ["Lógica implacável", "Praticidade", "Honestidade direta", "Independência intelectual"],
    desc: "Alhaitham prefere a verdade nua e crua a qualquer formalidade social, guiando-se sempre pela razão. Assim como ele, você valoriza clareza e eficiência acima de qualquer aparência.",
    quote: "\u201CFatos não precisam da sua aprovação para serem verdadeiros.\u201D",
    image: "assets/characters/alhaitham.png",
  },
  klee: {
    key: "klee", name: "Klee", element: "pyro", region: "Mondstadt",
    title: "A Bruxa Kamera do Espetáculo",
    traits: ["Curiosidade explosiva", "Inocência", "Alegria contagiante", "Criatividade"],
    desc: "Klee encara o mundo com uma curiosidade explosiva e uma alegria genuína, mesmo quando as coisas viram (literalmente) de cabeça para baixo. Você também sabe encontrar diversão nos momentos mais inesperados.",
    quote: "\u201CBum! Isso foi divertido, vamos de novo?\u201D",
    image: "assets/characters/klee.png",
  },
};
const CHARACTER_KEYS = Object.keys(CHARACTERS);
/* Ordem usada apenas para desempate determinístico de pontuação */
const CHARACTER_TIEBREAK_ORDER = [
  "zhongli","alhaitham","xiao","klee","yaemiko","raiden","hutao","nahida",
  "venti","wanderer","navia","ayaka","arlecchino","furina","kazuha","neuvillette",
];

/* ------------------- REGIÕES (Quiz "Onde em Teyvat você deveria viver?") ------------------- */
const REGIONS = {
  mondstadt: {
    key: "mondstadt", name: "Mondstadt", element: "anemo",
    kicker: "A Cidade da Liberdade",
    desc: "Você valoriza a liberdade acima de quase tudo, encontra alegria nas coisas simples e não gosta de amarras — sejam elas regras, tradições ou expectativas alheias. Mondstadt, com seus ventos livres e taças erguidas, seria seu verdadeiro lar.",
    traits: ["Liberdade", "Simplicidade", "Espírito boêmio", "Comunidade acolhedora"],
    quote: "\u201COnde o vento sopra livre, ali está o meu lar.\u201D",
    image: "assets/regions/mondstadt.jpg",
    atmosphere: "Colinas verdes, moinhos de vento girando ao longe e o som constante de taças brindando nas tabernas.",
    curiosities: ["É conhecida como a \"Cidade da Liberdade\" por seus habitantes valorizarem tanto a individualidade.", "As festividades e vinícolas fazem parte do dia a dia da cidade."],
  },
  liyue: {
    key: "liyue", name: "Liyue", element: "geo",
    kicker: "O Porto dos Contratos",
    desc: "Você respeita tradição, valoriza a palavra dada e acredita que contratos bem construídos sustentam a confiança entre as pessoas. Liyue, com sua história milenar e comércio próspero, combinaria perfeitamente com o seu jeito de ser.",
    traits: ["Tradição", "Senso de contrato", "Prosperidade", "Respeito pela história"],
    quote: "\u201CUm bom contrato vale mais que mil promessas.\u201D",
    image: "assets/regions/liyue.jpg",
    atmosphere: "Portos movimentados, formações rochosas imponentes e a tradição do comércio em cada esquina.",
    curiosities: ["É famosa por sua arquitetura inspirada em contratos e acordos antigos.", "O comércio e a gastronomia são parte fundamental da identidade da região."],
  },
  inazuma: {
    key: "inazuma", name: "Inazuma", element: "electro",
    kicker: "A Nação Eterna",
    desc: "Disciplina, honra e um certo apreço pela estética refinada guiam suas escolhas. Inazuma, entre suas ilhas eternas e códigos rígidos de conduta, seria o cenário perfeito para a sua busca por excelência.",
    traits: ["Disciplina", "Honra", "Tradição refinada", "Determinação silenciosa"],
    quote: "\u201CA eternidade se constrói com disciplina, dia após dia.\u201D",
    image: "assets/regions/inazuma.jpg",
    atmosphere: "Ilhas cercadas por raios e tempestades, com templos antigos e uma estética entre o tradicional e o sobrenatural.",
    curiosities: ["É formada por um arquipélago de ilhas, cada uma com sua própria atmosfera.", "A cultura local mistura fortemente tradição, honra e disciplina."],
  },
  sumeru: {
    key: "sumeru", name: "Sumeru", element: "dendro",
    kicker: "A Nação da Sabedoria",
    desc: "Sua curiosidade nunca descansa, e você está sempre em busca de aprender algo novo sobre o mundo e sobre si mesmo. Sumeru, entre florestas vivas e desertos ancestrais, alimentaria sua sede por conhecimento.",
    traits: ["Curiosidade", "Sabedoria", "Diversidade", "Crescimento pessoal"],
    quote: "\u201CTodo conhecimento começa com uma pergunta sincera.\u201D",
    image: "assets/regions/sumeru.jpg",
    atmosphere: "Florestas luminescentes de um lado, dunas desérticas do outro — dois biomas completamente opostos numa só nação.",
    curiosities: ["Reúne tanto uma floresta tropical quanto um deserto árido dentro do mesmo território.", "É associada ao conhecimento, à pesquisa e à sabedoria acumulada."],
  },
  fontaine: {
    key: "fontaine", name: "Fontaine", element: "hydro",
    kicker: "A Nação da Justiça",
    desc: "Você acredita profundamente em justiça e verdade, mesmo quando isso significa questionar as próprias regras. Fontaine, com seus tribunais e sua elegância aquática, combinaria com seu senso de certo e errado.",
    traits: ["Justiça", "Elegância", "Inovação", "Verdade acima da aparência"],
    quote: "\u201CA verdade, como a água, sempre encontra seu nível.\u201D",
    image: "assets/regions/fontaine.jpg",
    atmosphere: "Canais de água cristalina, arquitetura elegante e uma atmosfera que lembra tribunais e teatros grandiosos.",
    curiosities: ["É fortemente ligada à ideia de justiça e ao sistema judiciário.", "A estética aquática e teatral está presente em praticamente toda a região."],
  },
  natlan: {
    key: "natlan", name: "Natlan", element: "pyro",
    kicker: "A Nação da Chama e da Guerra",
    desc: "Coragem, paixão e um espírito competitivo movem você todos os dias. Natlan, terra de tribos guerreiras e vulcões ativos, seria o lugar onde sua energia intensa finalmente encontraria espaço para arder livremente.",
    traits: ["Coragem", "Paixão", "Espírito competitivo", "Vida em comunidade"],
    quote: "\u201CA chama que arde mais forte nunca teme o vento.\u201D",
    image: "assets/regions/natlan.jpg",
    atmosphere: "Vulcões ativos, terras vibrantes e uma cultura tribal cheia de energia e competitividade saudável.",
    curiosities: ["É associada a tribos guerreiras e festividades cheias de energia.", "A paisagem vulcânica contrasta com a vida vibrante da população."],
  },
  snezhnaya: {
    key: "snezhnaya", name: "Snezhnaya", element: "cryo",
    kicker: "A Nação da Vontade Inabalável",
    desc: "Você é resiliente, ambicioso(a) e não se abala fácil, mesmo diante do frio mais implacável — seja ele literal ou figurado. Snezhnaya, misteriosa e imponente, combinaria com sua força silenciosa e sua vontade inquebrável.",
    traits: ["Resiliência", "Ambição", "Mistério", "Força silenciosa"],
    quote: "\u201CO gelo não quebra; ele apenas espera o momento certo.\u201D",
    image: "assets/regions/snezhnaya.jpg",
    atmosphere: "Neve interminável, paisagens imponentes e uma aura de mistério que poucos conseguem realmente decifrar.",
    curiosities: ["É uma das regiões menos exploradas e mais misteriosas de Teyvat.", "Está associada a uma vontade inabalável mesmo diante do frio mais extremo."],
  },
};
const REGION_KEYS = Object.keys(REGIONS);
const REGION_TIEBREAK_ORDER = ["liyue","snezhnaya","sumeru","mondstadt","natlan","inazuma","fontaine"];

/* ------------------- DADOS DO CRIADOR DE PERSONAGEM ------------------- */
const WEAPONS = ["Espada", "Espadão", "Lança", "Arco", "Catalisador"];
const ROLES = ["DPS", "Sub-DPS", "Suporte", "Healer", "Shielder"];
const RARITIES = [4, 5];

const CREATOR_NAME_POOL = [
  "Kaelen", "Isolde", "Ryvenna", "Thalos", "Mireth", "Sable", "Corvin", "Elowen",
  "Draven", "Liora", "Baelor", "Nyxara", "Soren", "Wrenna", "Talvin", "Aeris",
];
const CREATOR_PERSONALITY_POOL = [
  "Corajoso(a) e leal, sempre pronto(a) para proteger os amigos.",
  "Misterioso(a) e calculista, fala pouco mas observa tudo.",
  "Alegre e brincalhão(a), traz leveza para qualquer grupo.",
  "Calmo(a) e sábio(a), busca entender antes de agir.",
  "Ambicioso(a) e determinado(a), nunca desiste de um objetivo.",
  "Gentil e protetor(a), coloca os outros sempre em primeiro lugar.",
  "Rebelde e independente, segue apenas as próprias regras.",
  "Elegante e reservado(a), esconde um coração caloroso.",
];
const CREATOR_PHRASE_POOL = [
  "Vamos além dos limites, juntos.",
  "Nenhum obstáculo é grande demais.",
  "Que os ventos guiem nossos passos.",
  "A verdade sempre prevalece.",
  "Coragem é a chama que nunca se apaga.",
  "A sabedoria vem de quem ousa perguntar.",
  "Cada jornada começa com um passo firme.",
];
const CREATOR_CONSTELLATION_PREFIXES = ["Ventus", "Ignis", "Glacies", "Terra", "Fulgur", "Aqua", "Silva", "Umbra", "Lux", "Nox"];
const CREATOR_CONSTELLATION_SUFFIXES = ["Aeternum", "Nocturna", "Silentium", "Immota", "Arcanum", "Serenus", "Sapientae", "Infinitus", "Devotus", "Gloriae"];

/* ------------------- SIMULADOR DE DESEJOS ------------------- */
/* Puramente para entretenimento. Taxas e raridades fictícias, sem
   qualquer relação com as probabilidades reais de Genshin Impact,
   sem dinheiro real, compras ou apostas. */
const WISH_ITEMS = {
  common: ELEMENT_KEYS.map(k => ({
    key: `common-${k}`, tier: 3, element: k,
    name: `Fragmento de Visão ${ELEMENTS[k].name}`,
    image: ELEMENTS[k].vision,
  })),
  rare: ELEMENT_KEYS.map(k => ({
    key: `rare-${k}`, tier: 4, element: k,
    name: `Cristal Elemental ${ELEMENTS[k].name}`,
    image: ELEMENTS[k].vision,
  })),
  legendary: CHARACTER_KEYS.map(k => ({
    key: `legend-${k}`, tier: 5, element: CHARACTERS[k].element,
    name: CHARACTERS[k].name,
    image: CHARACTERS[k].image,
  })),
};
/* Taxas fictícias, só para a brincadeira ter emoção — não representam o jogo oficial. */
const WISH_RATES = { legendary: 0.03, rare: 0.13, common: 0.84 };

/* ------------------- COMPATIBILIDADE ELEMENTAL ------------------- */
/* Puramente para entretenimento — inspirada nas reações elementais e
   ressonâncias do jogo, mas NÃO é uma avaliação psicológica real. */
const ELEMENT_COMPATIBILITY = {
  "pyro-pyro": { percent: 88, title: "Duas Chamas, Um Só Incêndio",
    strengths: ["Paixão mútua e intensa", "Nunca faltam energia ou motivação", "Cumplicidade nas grandes decisões"],
    conflicts: ["Tendência a discussões acaloradas", "Dificuldade em ceder primeiro"],
    dynamic: "Duas almas movidas pela mesma intensidade — juntas, vocês incendeiam qualquer ambiente, para o bem e para o mal.",
    quote: "\u201COnde uma chama não basta, duas iluminam o caminho inteiro.\u201D" },
  "pyro-hydro": { percent: 91, title: "Vapor: Transformação Mútua",
    strengths: ["Equilíbrio entre intensidade e sensibilidade", "Crescimento mútuo através da diferença", "Química instantânea e poderosa"],
    conflicts: ["Personalidades opostas podem confundir expectativas", "Um pode se sentir sufocado pela intensidade do outro"],
    dynamic: "Fogo e água se transformam um ao outro — essa dupla tem potencial explosivo para o crescimento, desde que aprendam a dosar a intensidade.",
    quote: "\u201CJuntos, viramos vapor: algo novo, mais forte que os dois separados.\u201D" },
  "pyro-anemo": { percent: 82, title: "Vento que Espalha o Fogo",
    strengths: ["Aventuras cheias de energia", "Liberdade com propósito", "Boa capacidade de se reinventar juntos"],
    conflicts: ["Um pode buscar estabilidade que o outro não oferece", "Combustão de planos mal alinhados"],
    dynamic: "O vento carrega as chamas para novos lugares — essa dupla nunca fica parada, mas precisa de direção para não se dispersar.",
    quote: "\u201CO vento não apaga o fogo — ele o espalha ainda mais longe.\u201D" },
  "pyro-electro": { percent: 74, title: "Explosão Inevitável",
    strengths: ["Energia contagiante", "Nunca é uma relação monótona", "Grandes ideias nascem da combinação"],
    conflicts: ["Risco real de atrito constante", "Dificuldade em manter a calma em desacordos"],
    dynamic: "Essa combinação é puro fogo de artifício: emocionante, cheia de faíscas, mas que pede cuidado para não sair do controle.",
    quote: "\u201CQuando a chama encontra a centelha, o resultado nunca é discreto.\u201D" },
  "pyro-dendro": { percent: 78, title: "Combustão Lenta e Constante",
    strengths: ["Crescimento mútuo sustentado", "Paciência que alimenta paixão", "Apoio nos momentos difíceis"],
    conflicts: ["O ritmo de cada um pode ser bem diferente", "Um pode consumir a energia do outro sem perceber"],
    dynamic: "Uma chama que se alimenta lentamente da vegetação ao redor — juntos, vocês crescem aos poucos, mas de forma duradoura.",
    quote: "\u201CO fogo que queima devagar é o que dura mais tempo.\u201D" },
  "pyro-cryo": { percent: 89, title: "O Degelo Inevitável",
    strengths: ["Contraste que se completa", "Um traz calor onde o outro traz calma", "Equilíbrio emocional surpreendente"],
    conflicts: ["Diferenças de temperamento podem gerar mal-entendidos", "Um pode achar o outro intenso ou frio demais"],
    dynamic: "O calor de um derrete as defesas do outro aos poucos — uma dupla clássica de opostos que se encontram no meio do caminho.",
    quote: "\u201CNem todo gelo resiste ao calor certo.\u201D" },
  "pyro-geo": { percent: 80, title: "Fogo Protegido por Pedra",
    strengths: ["Estabilidade para a paixão", "Proteção mútua", "Bases sólidas para grandes planos"],
    conflicts: ["Ritmos diferentes de decisão", "Um pode achar o outro teimoso demais"],
    dynamic: "A paixão de um ganha forma e proteção com a firmeza do outro — juntos, constroem algo que dura.",
    quote: "\u201CA chama mais forte é aquela protegida por muros firmes.\u201D" },
  "hydro-hydro": { percent: 87, title: "Duas Correntes, Um Só Rio",
    strengths: ["Empatia profunda e mútua", "Comunicação emocional fácil", "Cuidado natural um com o outro"],
    conflicts: ["Podem evitar conflitos necessários", "Excesso de acomodação mútua"],
    dynamic: "Duas correntes que fluem na mesma direção — juntos, formam um rio calmo, profundo e constante.",
    quote: "\u201CComo a água encontra a água, vocês sempre encontram um ao outro.\u201D" },
  "hydro-anemo": { percent: 84, title: "Correnteza ao Vento",
    strengths: ["Adaptação natural um ao outro", "Liberdade emocional", "Boa capacidade de recomeçar juntos"],
    conflicts: ["Falta de raízes firmes em momentos de crise", "Podem evitar compromissos importantes"],
    dynamic: "A água segue o vento sem resistência — uma dupla fluida, que se adapta com facilidade a qualquer direção da vida.",
    quote: "\u201CO vento não teme a água — ele a leva para onde for preciso.\u201D" },
  "hydro-electro": { percent: 79, title: "Corrente Elétrica na Água",
    strengths: ["Energia constante na relação", "Nunca faltam assuntos ou estímulos", "Boa capacidade de motivar um ao outro"],
    conflicts: ["Excesso de estímulo pode cansar", "Um pode se sentir exposto pela intensidade do outro"],
    dynamic: "A eletricidade se propaga rápido na água — essa dupla vive momentos intensos e conectados, mas precisa de pausas para recarregar.",
    quote: "\u201CA corrente encontra caminho até onde a água alcança.\u201D" },
  "hydro-dendro": { percent: 93, title: "Florescimento Mútuo",
    strengths: ["Crescimento conjunto genuíno", "Cuidado que se transforma em evolução", "Parceria naturalmente equilibrada"],
    conflicts: ["Podem crescer rápido demais sem perceber mudanças um no outro", "Excesso de zelo pode sufocar"],
    dynamic: "A água nutre a vida ao redor — juntos, vocês florescem de um jeito raro de se ver, com apoio mútuo genuíno.",
    quote: "\u201COnde a água toca a vida, algo novo sempre desabrocha.\u201D" },
  "hydro-cryo": { percent: 71, title: "Águas Paradas no Tempo",
    strengths: ["Momentos de calma profunda juntos", "Respeito mútuo pelo espaço do outro", "Estabilidade emocional"],
    conflicts: ["Risco de estagnação emocional", "Dificuldade em tomar iniciativa juntos"],
    dynamic: "A água se cristaliza no encontro com o frio — uma dupla que precisa de cuidado para não deixar a relação congelar no tempo.",
    quote: "\u201CNem toda água parada está morta — algumas só esperam o degelo certo.\u201D" },
  "hydro-geo": { percent: 81, title: "Águas que Moldam a Pedra",
    strengths: ["Paciência mútua", "Construção sólida com o tempo", "Cuidado que se transforma em confiança"],
    conflicts: ["Ritmos de mudança muito diferentes", "Um pode parecer rígido demais para o outro"],
    dynamic: "A água, com tempo e paciência, molda até a pedra mais dura — uma dupla que se constrói aos poucos, mas com solidez rara.",
    quote: "\u201CA gota que insiste, um dia molda até a montanha.\u201D" },
  "anemo-anemo": { percent: 76, title: "Dois Ventos Livres",
    strengths: ["Liberdade mútua respeitada", "Nunca faltam novas aventuras", "Fácil adaptação a mudanças"],
    conflicts: ["Dificuldade em criar raízes juntos", "Podem se afastar sem perceber"],
    dynamic: "Dois ventos que sopram livres — uma dupla emocionante, mas que precisa de esforço consciente para não se dispersar.",
    quote: "\u201CO vento que segue sozinho vai longe; o que sopra em dupla, vai mais alto.\u201D" },
  "anemo-electro": { percent: 77, title: "Tempestade em Movimento",
    strengths: ["Energia imprevisível e divertida", "Nunca é uma relação parada", "Boa capacidade de se reinventar"],
    conflicts: ["Excesso de imprevisibilidade pode cansar", "Falta de planejamento conjunto"],
    dynamic: "O vento carrega a eletricidade para todos os lados — juntos, formam uma tempestade animada, mas volátil.",
    quote: "\u201CNem toda tempestade destrói; algumas só sacodem o que estava parado demais.\u201D" },
  "anemo-dendro": { percent: 85, title: "Sementes ao Vento",
    strengths: ["Ideias que se espalham e crescem", "Boa capacidade de inspirar um ao outro", "Crescimento através da liberdade"],
    conflicts: ["Um pode buscar estabilidade que o outro não oferece", "Planos podem se perder no caminho"],
    dynamic: "O vento carrega sementes para florescerem em novos lugares — uma dupla que cresce justamente por não se prender a um só lugar.",
    quote: "\u201CToda semente precisa de um vento que a leve para onde possa crescer.\u201D" },
  "anemo-cryo": { percent: 83, title: "Brisa Gelada",
    strengths: ["Clareza mental compartilhada", "Respeito mútuo pela independência", "Equilíbrio entre movimento e calma"],
    conflicts: ["Podem parecer distantes um do outro às vezes", "Dificuldade em expressar necessidades"],
    dynamic: "O vento carrega o frio para onde quiser — uma dupla serena, que valoriza espaço e liberdade tanto quanto a companhia.",
    quote: "\u201CNem toda brisa precisa ser quente para ser bem-vinda.\u201D" },
  "anemo-geo": { percent: 80, title: "Liberdade com Raízes",
    strengths: ["Equilíbrio entre movimento e estabilidade", "Um ensina o outro a se adaptar ou se firmar", "Parceria complementar rara"],
    conflicts: ["Visões de vida muito diferentes", "Um pode se sentir preso, o outro perdido"],
    dynamic: "O vento aprende a pousar, a pedra aprende a se mover — uma dupla que se equilibra justamente pelas diferenças.",
    quote: "\u201CAté o vento mais livre, às vezes, precisa de um lugar para pousar.\u201D" },
  "electro-electro": { percent: 75, title: "Alta Voltagem",
    strengths: ["Energia e ambição compartilhadas", "Nunca faltam ideias ou estímulos", "Boa capacidade de se desafiarem mutuamente"],
    conflicts: ["Competitividade pode virar rivalidade", "Excesso de intensidade em desacordos"],
    dynamic: "Duas fontes de energia na mesma direção — essa dupla é elétrica, literalmente, e precisa aprender a canalizar essa força.",
    quote: "\u201CDuas centelhas juntas iluminam mais do que imaginam.\u201D" },
  "electro-dendro": { percent: 90, title: "Catalisadores um do Outro",
    strengths: ["Estímulo mútuo ao crescimento", "Ideias que se transformam rápido em ação", "Parceria intelectualmente estimulante"],
    conflicts: ["Ritmo acelerado pode cansar", "Podem pular etapas importantes juntos"],
    dynamic: "A energia acelera o crescimento — juntos, vocês se tornam catalisadores um do desenvolvimento do outro.",
    quote: "\u201CUma ideia parada só precisa da centelha certa para florescer.\u201D" },
  "electro-cryo": { percent: 68, title: "Curto-Circuito Gelado",
    strengths: ["Contraste que desperta curiosidade mútua", "Aprendizado constante um com o outro", "Nunca é uma relação óbvia"],
    conflicts: ["Choque de temperamentos frequente", "Dificuldade em encontrar um meio-termo"],
    dynamic: "O frio e a eletricidade não combinam facilmente — essa dupla exige esforço extra para transformar o choque inicial em conexão real.",
    quote: "\u201CNem toda faísca precisa incendiar; algumas só iluminam por um instante.\u201D" },
  "electro-geo": { percent: 79, title: "Energia Contida em Pedra",
    strengths: ["Estabilidade para grandes ideias", "Proteção mútua nos momentos difíceis", "Equilíbrio entre ação e ponderação"],
    conflicts: ["Ritmos de decisão muito diferentes", "Um pode achar o outro impulsivo ou lento demais"],
    dynamic: "A energia ganha forma quando encontra estrutura — uma dupla que transforma impulso em algo concreto e duradouro.",
    quote: "\u201CA energia mais poderosa é aquela que sabe onde se firmar.\u201D" },
  "dendro-dendro": { percent: 86, title: "Raízes Entrelaçadas",
    strengths: ["Crescimento mútuo constante", "Paciência e compreensão profundas", "Cumplicidade natural e silenciosa"],
    conflicts: ["Podem evitar confrontos necessários", "Excesso de acomodação mútua"],
    dynamic: "Duas raízes que crescem entrelaçadas — uma dupla que se fortalece com o tempo, de forma silenciosa e constante.",
    quote: "\u201CNenhuma árvore forte cresceu sozinha; todas têm raízes entrelaçadas a outras.\u201D" },
  "dendro-cryo": { percent: 77, title: "Silêncio que Fala Alto",
    strengths: ["Cumplicidade sem muitas palavras", "Respeito profundo pelo espaço um do outro", "Crescimento através da reflexão conjunta"],
    conflicts: ["Comunicação pode ser indireta demais", "Sentimentos podem ficar mal-expressos"],
    dynamic: "Duas naturezas contemplativas que se entendem no silêncio — uma dupla que floresce longe do barulho, no seu próprio tempo.",
    quote: "\u201CNem tudo que cresce faz barulho; algumas raízes se aprofundam em silêncio.\u201D" },
  "dendro-geo": { percent: 84, title: "Crescimento Sobre Bases Firmes",
    strengths: ["Estabilidade para o crescimento mútuo", "Paciência compartilhada", "Confiança que se constrói aos poucos"],
    conflicts: ["Ritmo lento pode frustrar planos urgentes", "Resistência a mudanças necessárias"],
    dynamic: "Toda vida forte precisa de solo firme — essa dupla cresce devagar, mas constrói algo que dificilmente se abala.",
    quote: "\u201CA árvore mais alta é a que tem as raízes mais profundas.\u201D" },
  "cryo-cryo": { percent: 82, title: "Duas Calmas, Um Só Inverno",
    strengths: ["Entendimento mútuo sem esforço", "Paz e estabilidade emocional", "Respeito profundo pela individualidade"],
    conflicts: ["Dificuldade em tomar iniciativa juntos", "Podem se distanciar emocionalmente sem perceber"],
    dynamic: "Duas naturezas serenas que se entendem sem precisar de muitas palavras — uma dupla tranquila, mas que precisa de calor ocasional.",
    quote: "\u201CNem todo silêncio é distância; às vezes, é só paz compartilhada.\u201D" },
  "cryo-geo": { percent: 85, title: "Gelo Talhado em Pedra",
    strengths: ["Estabilidade emocional mútua", "Confiança construída aos poucos, mas firme", "Paciência compartilhada"],
    conflicts: ["Podem demorar demais para agir juntos", "Dificuldade em expressar afeto abertamente"],
    dynamic: "O frio e a pedra criam algo raro e resistente — uma dupla que não se abala fácil, e que se fortalece com o tempo.",
    quote: "\u201CO que resiste ao gelo e à pedra, resiste a quase tudo.\u201D" },
  "geo-geo": { percent: 90, title: "Duas Montanhas, Uma Só Cordilheira",
    strengths: ["Confiabilidade mútua absoluta", "Estabilidade emocional rara", "Compromisso duradouro"],
    conflicts: ["Teimosia dobrada em desacordos", "Resistência mútua a mudanças necessárias"],
    dynamic: "Duas montanhas lado a lado formam uma cordilheira inteira — uma dupla sólida, confiável, feita para durar.",
    quote: "\u201CMontanhas não se movem fácil, mas juntas, sustentam o mundo.\u201D" },
};

/* ------------------- CONQUISTAS ------------------- */
/* "available: true" = a atividade que desbloqueia essa conquista já existe no Portal.
   "available: false" = pertence a um módulo ainda não implementado (aparece como ???). */
const ACHIEVEMENTS = [
  {
    id: "primeira-visao", name: "Primeira Visão",
    description: "Complete o Quiz Elemental.",
    available: true,
  },
  {
    id: "fotografo-fontaine", name: "Fotógrafo de Fontaine",
    description: "Gere seu primeiro card em PNG.",
    available: true,
  },
  {
    id: "arquivista", name: "Arquivista",
    description: "Salve 5 cards na Galeria.",
    available: true,
  },
  {
    id: "lugar-para-chamar-de-lar", name: "Um Lugar para Chamar de Lar",
    description: "Descubra sua região em Teyvat.",
    available: true,
  },
  {
    id: "destinos-entrelacados", name: "Destinos Entrelaçados",
    description: "Descubra seu personagem compatível.",
    available: true,
  },
  {
    id: "artesao-de-teyvat", name: "Artesão de Teyvat",
    description: "Crie seu primeiro personagem.",
    available: true,
  },
  {
    id: "sob-as-estrelas", name: "Sob as Estrelas",
    description: "Faça seu primeiro Desejo.",
    available: true,
  },
  {
    id: "dez-destinos", name: "Dez Destinos",
    description: "Faça um Desejo x10.",
    available: true,
  },
  {
    id: "alquimia-elemental", name: "Alquimia Elemental",
    description: "Teste uma Compatibilidade Elemental.",
    available: true,
  },
  {
    id: "explorador-de-teyvat", name: "Explorador de Teyvat",
    description: "Utilize todas as principais experiências do Portal.",
    available: false,
  },
];

/* ------------------- ATIVIDADES DO MENU PRINCIPAL ------------------- */
/* status: "available" já é navegável de verdade.
   status: "soon" mostra uma tela honesta de "Em breve", sem fingir funcionalidade. */
const ACTIVITIES = [
  {
    id: "elemental-quiz",
    title: "Descobrir minha Visão",
    blurb: "Responda 20 perguntas e descubra qual dos sete elementos combina com você.",
    route: "quiz-intro",
    status: "available",
  },
  {
    id: "character-quiz",
    title: "Qual personagem combina comigo?",
    blurb: "Um quiz de personalidade para descobrir seu companheiro de jornada ideal.",
    route: "character-quiz-intro",
    status: "available",
  },
  {
    id: "region-quiz",
    title: "Qual região de Teyvat combina comigo?",
    blurb: "Descubra onde em Teyvat você deveria viver.",
    route: "region-quiz-intro",
    status: "available",
  },
  {
    id: "character-creator",
    title: "Criar meu Personagem",
    blurb: "Monte um personagem original de Genshin do zero.",
    route: "creator-intro",
    status: "available",
  },
  {
    id: "vision-generator",
    title: "Criar minha Visão",
    blurb: "Gere uma Visão personalizada com nome, elemento e região.",
    route: "vision-generator-intro",
    status: "available",
  },
  {
    id: "wish-simulator",
    title: "Simulador de Desejos",
    blurb: "Uma brincadeira visual inspirada no sistema de Wishes — sem dinheiro real.",
    route: "wish-intro",
    status: "available",
  },
  {
    id: "compatibility",
    title: "Compatibilidade Elemental",
    blurb: "Compare duas Visões e descubra a dinâmica da dupla, por diversão.",
    route: "compat-intro",
    status: "available",
  },
  {
    id: "encyclopedia",
    title: "Elementos de Teyvat",
    blurb: "Uma enciclopédia com os sete elementos e suas características.",
    route: "encyclopedia",
    status: "available",
  },
  {
    id: "map",
    title: "Mapa de Teyvat",
    blurb: "Explore as sete nações de Teyvat.",
    route: "map",
    status: "available",
  },
  {
    id: "profile",
    title: "Meu Perfil",
    blurb: "Veja tudo o que você já descobriu sobre o seu viajante.",
    route: "profile",
    status: "available",
  },
  {
    id: "achievements",
    title: "Conquistas",
    blurb: "Acompanhe suas conquistas desbloqueadas no Portal.",
    route: "achievements",
    status: "available",
  },
  {
    id: "gallery",
    title: "Minha Galeria",
    blurb: "Reveja os cards e resultados que você salvou.",
    route: "gallery",
    status: "available",
  },
];

/* Mensagens aleatórias da tela de carregamento */
const LOADING_MESSAGES = [
  "Explorando Teyvat...",
  "Preparando a próxima jornada...",
  "Consultando as estrelas...",
  "Paimon está procurando o caminho...",
  "Carregando as memórias do viajante...",
];

/* ------------------- ENCICLOPÉDIA DOS ELEMENTOS ------------------- */
/* Reações elementais associadas a cada elemento, para a Enciclopédia. */
const ELEMENT_REACTIONS = {
  pyro: ["Vaporize (com Hydro)", "Melt (com Cryo)", "Overloaded (com Electro)", "Burning (com Dendro)", "Swirl (com Anemo)", "Crystallize (com Geo)"],
  hydro: ["Vaporize (com Pyro)", "Frozen (com Cryo)", "Electro-Charged (com Electro)", "Bloom (com Dendro)", "Swirl (com Anemo)", "Crystallize (com Geo)"],
  anemo: ["Swirl (com qualquer elemento reativo)"],
  electro: ["Overloaded (com Pyro)", "Superconduct (com Cryo)", "Electro-Charged (com Hydro)", "Quicken (com Dendro)", "Swirl (com Anemo)", "Crystallize (com Geo)"],
  dendro: ["Burning (com Pyro)", "Bloom (com Hydro)", "Quicken (com Electro)", "Swirl (com Anemo)"],
  cryo: ["Melt (com Pyro)", "Frozen (com Hydro)", "Superconduct (com Electro)", "Swirl (com Anemo)", "Crystallize (com Geo)"],
  geo: ["Crystallize (com qualquer elemento reativo)"],
};
